config/routes.rb
Rails.application.routes.draw do
  get 'applies/index'
  post 'applies/filter', to:'applies#filter'
  get 'applies/create'
  delete 'applies/destroy'
  get 'applies/show'
  get 'applies/verify' ,to:'applies#verify'
  get '/verifyotp', to:'applies#verifyotp'
  # resources :applies
  resources :jobs
  get 'applied_job', to:'jobs#applied_job'
  get 'applicants/index'
  get 'applicants/new'
  get 'applicants/show'
  get 'applicants/create'
  get 'employees/new'
  get 'applies/accept'
  get 'applies/rejected'
  get 'search', to: 'applicants#index'
  devise_for :employees
  devise_for :applicants 
  devise_scope :applicant do
    get 'sign_in', to: 'devise/sessions#new'
  end
  root 'static_pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    # @job = current_employee.jobs.build if employee_signed_in?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
  <% if employee_signed_in? %>
    <div class="center1">
      <h1 style="color:black">Creat new Job here</h1> 
      <%= link_to 'Create a new job',new_job_path,class:'btn btn-lg btn-primary'%>
    </div>

  <%elsif applicant_signed_in?%>
    <div class="center">
      
        <h1 style="color:black">Hello, <%=current_applicant.name%></h1>
        <%= link_to 'New Jobs for you',jobs_path,class:'btn btn-lg btn-dark'%>
        <%#<%= link_to 'Job_statu',applicant.applies.job,class:'btn btn-secondary my-2'%>
    
   </div>
  <%else%>

    <!DOCTYPE html>
    <html>
      <head>
        <title>Jober Home Page</title>
      </head>
      <body style="text-align: center !important; width: 60%; margin: 0 auto; margin: auto !important;">

        <div>
            <h1>Welcom to the Jober app</h1>
  
            <h2>Who are you</h2>
            <%= link_to 'Employee',employees_new_path,class:"btn btn-lg btn-primary"%>
            <%= link_to 'Applicant',applicants_new_path,class:"btn btn-lg btn-primary"%>
        </div> 
      </body>
    </html> 
  <%end%>