config/routes.rb
Rails.application.routes.draw do
  get 'applies/index'
  post 'applies/filter', to:'applies#filter'
  get 'applies/create'
  delete 'applies/destroy'
  get 'applies/show'
  get 'applies/verify' ,to:'applies#verify'
  get '/verifyotp', to:'applies#verifyotp'
  # resources :applies
  resources :jobs
  get 'applied_job', to:'jobs#applied_job'
  get 'applicants/index'
  get 'applicants/new'
  get 'applicants/show'
  get 'applicants/create'
  get 'employees/new'
  get 'applies/accept'
  get 'applies/rejected'
  get 'search', to: 'applicants#index'
  devise_for :employees
  devise_for :applicants 
  devise_scope :applicant do
    get 'sign_in', to: 'devise/sessions#new'
  end
  root 'static_pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/applicant.rb
class Applicant < ApplicationRecord
  has_many :applies
  has_many :jobs ,through: :applies , dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true
  validates :skills, presence: true , length: {maximum: 140}
  validates :description, length: {maximum: 210}
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable 

  
  def apply(job)
    jobs<< job
  end 

end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  def index
    if current_employee   #it will show all the applicants who applied for a job to employee
      @job_application=Apply.where(job_id:params[:id])
    end
  end

  def new
    @applicant=Applicant.new
  end

  def show
    if current_employee
      @applicant=Applicant.find(params[:id])   #it will show the applicant's detail to employee
    elsif current_applicant
      @applicant=Applicant.find(current_applicant.id) #it will show the details of current applicant to current applicant
    end
  end
  def create
    @applicant=Applicant.new(params[:id])
    if @applicant.save
      loged_in @applicant
      redirect_to 'index'
    else
      render 'new'
    end
  end

  
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/views/applicants/_applicant_add.html.erb
<div class="field">
            <%= f.label :Full_Name %><br />
            <%= f.text_field :name, autofocus: true, autocomplete: "text" %>
          </div>
          <div class="field">
            <%= f.label :Add_Address %><br />
            <%= f.text_field :address, autofocus: true, autocomplete: "text" %>
          </div>
          <div class="field">
            <%= f.label :Skills %><br />
            <%= f.text_field :skills, autofocus: true, autocomplete: "text" %>
          </div>
          <div class="field">
            <%= f.label :Description %><br />
            <%= f.text_field :description, autofocus: true, autocomplete: "text" %>
</div>

app/views/applicants/edit.html.erb
<h1>Applicants#edit</h1>
<p>Find me in app/views/applicants/edit.html.erb</p>

app/views/applicants/index.html.erb
<p id="notice"><%= notice %></p>

<%if current_employee%>
  <h1>Hello <%= current_employee.email %></h1>
  <h1>It's All User Tables for this job </h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">User_info</th>
        <th scope="col">Status</th>
        <th scope="col">change_status</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <% @job_application.each do |application| %>
      <tbody>
        <% status=application_status(application.applicant.id,application.job.id)%>
        <tr>
          <td scope="row"><%= application.applicant.name %></td>
          <td scope="row"><%=application.applicant.email %></td>
          <td scope="row"><%= link_to 'Show', applicants_show_path(id:application.applicant.id),class:'btn btn-outline-primary'%></td>
          <td scope="row"><%=status%></td>
          <%if status=='hold'%>
            <td><%=link_to "Accept",applies_accept_path(jobs_id:application.job.id,user_id:application.applicant.id),class:'btn btn btn-primary'%>
            <%=link_to "Cancle",applies_rejected_path(user_id:application.applicant.id,jobs_id:application.job.id)%></td>
            <%after_status=application_status(application.applicant.id,application.job.id)%>
            
          <%else%>
            <td><%="It's already accepted you can't change the"%><td> <%#it's not permanent%>
          <%end%>
        </tr>
      </tbody>
    <%end%>
  </table>
        <%# <td><%= link_to 'Destroy', user, method: :delete,data: { confirm: 'Are you sure?' } %>
<%elsif current_applicant%>
  <div>
    <h1><%= current_applicant.name %></h1>
  </div>

  <%= link_to 'Show', applicants_show_path,class:'btn btn-lg btn-primary' %>
  <%= link_to 'Edit', applicants_edit_path,class:'btn btn-lg btn-primary'%>
  <%= link_to 'sign out', destroy_applicant_session_path,method: :delete ,class:'btn btn-lg btn-primary'%> 
<%else%>
  <h1>Please sign in Or Sing up</h1>
<%end%>

app/views/applicants/new.html.erb
<div class="row">
  <div class="col-md col-md-offset-3">
    <h1>Hello Here You can Find your Dream Job </h1>
    <h3>Are you existing User? 
    <%= link_to 'Log In',new_applicant_session_path,class:"btn btn-lg btn-primary"%>
    </h3>
    <br>
    <h3>Are you new user
    <%= link_to 'Sign Up',new_applicant_registration_path,class:"btn btn-lg btn-primary"%>
    </h3> 
  </div>
</div>

app/views/applicants/show.html.erb
<h1 style="color:blue;">Profile</h1>
<div class="htags">
  <div class="container">
    <ol>
      <h3 style="color:black;"> <li>Name-:<strong> <%=@applicant.name%></strong></li></h3>
      <h3 style="color:black"><li>Skills-:<strong> <%=@applicant.skills%></strong></li></h3>
      <h3 style="color:black"><li>Address-:<strong><%=@applicant.address%></strong></li></h3>
      <h3 style="color:black"><li>Details-:<strong><%=@applicant.description%></strong></li></h3>
    </ol>
    <%if current_applicant%>
      <%=link_to "Edit", edit_applicant_registration_path,method: :get, class:'btn btn-lg btn-outline-danger'%>
    <%end%>
  </div>
</div>

app/views/applicants/update.html.erb
<h1>Applicants#update</h1>
<p>Find me in app/views/applicants/update.html.erb</p>