config/routes.rb
Rails.application.routes.draw do
  get 'applies/index'
  post 'applies/filter', to:'applies#filter'
  get 'applies/create'
  delete 'applies/destroy'
  get 'applies/show'
  get 'applies/verify' ,to:'applies#verify'
  get '/verifyotp', to:'applies#verifyotp'
  # resources :applies
  resources :jobs
  get 'applied_job', to:'jobs#applied_job'
  get 'applicants/index'
  get 'applicants/new'
  get 'applicants/show'
  get 'applicants/create'
  get 'employees/new'
  get 'applies/accept'
  get 'applies/rejected'
  get 'search', to: 'applicants#index'
  devise_for :employees
  devise_for :applicants 
  devise_scope :applicant do
    get 'sign_in', to: 'devise/sessions#new'
  end
  root 'static_pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
  validates :job_title ,presence: true
  validates :experience ,presence: true
  validates :salary ,presence: true 
  belongs_to :employee ,foreign_key: 'employee_id'
  has_many :applies ,dependent: :destroy
  has_many :applicant,-> { distinct } ,through: :applies, dependent: :destroy
  paginates_per 5
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
include JobsHelper
  before_action :current_employee, only: [:create,:destroy,:edit,:update,:new,:index]
  before_action :current_applicant, only:[:index,:show]
  def index
    if employee_signed_in?
      @jobs=current_employee.jobs.page params[:page]
    elsif applicant_signed_in?
      @jobs=Job.page params[:page]
    end
  end

  def new
    @job=current_employee.jobs.build

  end

  def show
    if employee_signed_in?
      if valid_employee?(current_employee.id,params[:id])
        @job=Job.find(params[:id])
      else
        redirect_to jobs_path
      end
    elsif current_applicant
      @job=Job.find(params[:id])
    else
      redirect_to root_url
    end
  end
  def create
    @job=current_employee.jobs.build(job_params)
    if @job.save
      redirect_to root_url
    else
      redirect_to new
    end
  end

  def edit
    if valid_employee?(current_employee.id,params[:id])
      @job=Job.find(params[:id])
    else
      redirect_to root_url
    end
  end

  def update
    @job=Job.find_by(params[job_params])
    if @job.update(job_params)
      render 'show'
    else
      redirect_to edit
    end
  end

  def destroy
    if valid_employee?(current_employee.id,params[:id])
      @jobs=Job.find(params[:id])
      @jobs.destroy
      flash[:danger]= "Job deleted"
      redirect_to root_url
    end
  end
  private
    # def valid_applicant
    #   if applicant_signed_in?
    #     return errors.add(:base, "sorry it's not validated user") unless current_applicant
    #   else
    #     redirect_to root_url
    #   end 
    
    # end 
    # def valid_employee
    #   if current_employee
    #     render 'index'
    #   else
    #     return errors.add(:base, "sorry it's not validated user") unless current_employee
        
    #   end
    # end
    def job_params
      params.require(:job).permit(:job_title,:salary,:description,:experience)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def applied_job
    @jobs=Job.find_by(current_applicant)
  end
  def valid_employee?(employee_id,job_id)
    job=Job.find(job_id)
    if employee_id==job.employee_id
      true
    else
      false
    end
  end
  
end

app/views/jobs/_job_details.html.erb
<div class="container">
    <ul>
      <h3>Job Title-</h3> <h2><%=@job.job_title%></h2>
    </ul>
    <ul>
      <div>
        <h3>Job Description-</h3><h2><%=@job.description%></h2>
      </div>
    </ul>
    <ul>
      <div>
        <h3>Required Experinece-<h3><h4><%=@job.experience%> Years</h4> 
      </div>   
    </ul>
    <ul>
      <div><h3>Total CTC</h3> <h4> <%=@job.salary%>  LPA</h4></div> 
    </ul>
</div>

app/views/jobs/_job_form.html.erb
<%= form_with(model:@job, local:true) do |f| %>
   <%# <%= render 'devise/shared/error_messages',resource:f, object: f.object %> 
  <div class="field">
    <%=f.label :Job_title%>
    <%= f.text_area :job_title, placeholder: "Add Title to your post" %>
  </div>
  <div class="field">
    <%=f.label :Add_minimum_Requied_Experienced %>
    <%= f.text_area :experience ,placeholder: "add required experience" %>
  </div>
  <div class="field">
    <%=f.label :Add_salary_details %>
    <%= f.text_area :salary, placeholder: "add salary only integer" %>
  </div>
  <div class="field">
    <%=f.label :Add_description %>
    <%= f.text_area :description, placeholder: "add description" %>
  </div>
  <%= f.submit "Job", class: "btn btn-primary" %>
<%end%>

app/views/jobs/applied_job.html.erb
<div class="center1">
<%@jobs.each do |job|%>
  <h1><%=job.name%></h1>
<%end%>
</div>

app/views/jobs/edit.html.erb
<%=render 'job_form'%>

app/views/jobs/index.html.erb
<div><h3 >Jobs </h3></div>
<div class="row py-lg-5">
  <div class="col-lg-6 col-md-8 mx-auto">
  <table class="table">
    <thead>
     <tr>
        <th scope="col">Job_number</th>
        <th scope="col">Job_name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <%i=0%>
    <%@jobs.each do |job|%>
        <%i=i+1%> 
        <tbody>
          <h1>
          <tr>
            <h1><td scope="row"><%=i %></td></h1>
            <h1><td scope="row"><%=link_to job.job_title,job_path(job.id)%></td></h1>     
          </tr>
          </h1>
        </tbody>
    <%end%>
  </table>
  <%=paginate @jobs%>
  </div>
</div>

app/views/jobs/new.html.erb
<%if current_employee%>
  <h1> create New job here </h1>
  <%=render 'job_form',job:@job%>
<%end%>

app/views/jobs/show.html.erb
<div ,class="row py-lg-5">
  <%=render 'jobs/job_details'%>
  <%if current_applicant%>
    <%if is_applied(current_applicant.id,@job.id)%>
      <h1 style="color:blue"> <%='You had Already Applied for this job'%></h1>
      <h1> Click here to cancle your application  <%= link_to "Cancle_application",applies_destroy_path(id:@job.id),method: :delete, data:{confirm: "Are you sure?"},class:'btn btn-warning'%>   </h1>
     
    <%else%>  
      <div>
        <h1 style="color:red">Click here to apply for this job</h1> <%=link_to "Apply_Now",applies_verify_path(job_id:@job.id ) ,method: :get,class:'btn btn-lg btn-primary'%>
        <%#<h1 style="color:red">Click here to apply for this job</h1> <%=link_to "Apply_Now",applies_create_path(job_id:@job.id ) ,method: :post,class:'btn btn-lg btn-primary'%>
      </div>
    <%end%>
  <%elsif current_employee%>
  <div class="center1">
    <div>
      <%=link_to 'Edit job', edit_job_path(id:@job.id),class:'btn btn-lg btn-primary'%>
    </div>
    <div>
      <h1>
      <%=link_to 'Total_Applications',applicants_index_path(id:@job.id),class:'btn btn-info'%>
      </h1>
    </div>
    <div>
      <%=link_to 'Delete job', job_path(id:@job.id),method: :delete, data:{confirm: "Are you sure?"},class: 'btn btn-danger'%>
    </div>
  </div>
  <%end%>
</div>

app/views/jobs/update.html.erb
<h1>Jobs#update</h1>
<p>Find me in app/views/jobs/update.html.erb</p>