config/routes.rb
Rails.application.routes.draw do
  get 'applies/index'
  post 'applies/filter', to:'applies#filter'
  get 'applies/create'
  delete 'applies/destroy'
  get 'applies/show'
  get 'applies/verify' ,to:'applies#verify'
  get '/verifyotp', to:'applies#verifyotp'
  # resources :applies
  resources :jobs
  get 'applied_job', to:'jobs#applied_job'
  get 'applicants/index'
  get 'applicants/new'
  get 'applicants/show'
  get 'applicants/create'
  get 'employees/new'
  get 'applies/accept'
  get 'applies/rejected'
  get 'search', to: 'applicants#index'
  devise_for :employees
  devise_for :applicants 
  devise_scope :applicant do
    get 'sign_in', to: 'devise/sessions#new'
  end
  root 'static_pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
</header>
<nav class="navbar navbar-fixed-top navbar-inverse">
<div class="container">
  <a class="navbar-brand">Jober APP</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
 
    
        <% if employee_signed_in? %>
            
                <%= link_to 'Home',root_path %>
                <%= link_to 'Jobs',jobs_path%>
                <%= link_to 'Sign Out', destroy_employee_session_path, method: :delete%>
               
    
        <% elsif applicant_signed_in? %>
           
                
                    <li class="btn btn-outline-primary"><%= link_to 'Home',root_path%></li>
                    <li class="btn btn-outline-primary"><%= link_to 'Find New Jobs',jobs_path%></li>
                    <li class="btn btn-outline-primary"><%= link_to 'Profile/Edit',applicants_show_path%></li>
                    <li class="btn btn-outline-primary"><%= link_to 'My jobs /Status', applies_index_path%></li>
                    <li class="btn btn-outline-primary"><%= link_to 'Sign Out', destroy_applicant_session_path, method: :delete %></li>
           
        <% else %>
            <li class="nav-item">
                <%= link_to 'Home',root_path, class: 'nav-link' %>
            </li>

        <% end %>
   
</div>
</nav>
</header>